<?php
namespace Functions;
require_once __DIR__ . DIRECTORY_SEPARATOR . 'consts.php';
use const \Constants\{KEY, ALGO, LIFETIME, USER, DESTINATION};
use \DateTime;

/**
 * Gets desired user for cross-site login
 * @TODO Actually get desired user
 * @param Void
 * @return String User
 */
function get_user(): String
{
  return USER;
}

/**
 * Login user without password
 * @TODO Actually log the user in
 * @param  String $user Username
 * @return Bool         If login was successful
 */
function login(String $user): Bool
{
  return true;
}

/**
 * Redirect to a given $url
 * @param  String  $url       The URL to redirect to
 * @param  Bool    $permenant Whether or not it should be a permenant redirect
 * @return Void
 */
function redirect(String $url = '/', Bool $permanent = false): Void
{
  header(sprintf('Location: %s', $url), true, $permanent ? 301 : 302);
  exit();
}

/**
 * Checks if a list of $keys exist in $array
 * @param  Array  $array The array to check
 * @param  String $keys  The keys to check
 * @return Bool          Whether or not they exist
 * @example array_keys_exist($_GET, 'user', 'password')
 */
function array_keys_exist(Array $array, String ...$keys): Bool
{
  $exist = true;
  foreach($keys as $key) {
    if (! array_key_exists($key, $array)) {
      $exist = false;
      break;
    }
  }
  return $exist;
}

/**
 * Generate a query string for cross-site secure login
 * @param  String  $user        User
 * @param  String  $key         HMAC key
 * @param  String  $algo        Hashing algorithm
 * @return String               Generated query string, including the "?"
 */
function generate(
  String   $user,
  String   $key         = KEY,
  String   $algo        = ALGO
): String
{
  $datetime = new DateTime();
  $data = [
    'user'     => $user,
    'datetime' => $datetime->format(DateTime::W3C),
  ];
  $data['hmac'] = hash_hmac($algo, json_encode($data), $key);
  return '?' . http_build_query($data);
}

/**
 * Verifies parsed data generated by `generate`
 * @param  String   $user        User
 * @param  DateTime $datetime    Date request generated
 * @param  String   $hmac        Given hash to check against
 * @param  String   $key         HMAC key
 * @param  String   $algo        Hashing algorithm
 * @return Bool                  If data matches HMAC and it is not expired
 */
function verify(
  String   $user,
  DateTime $datetime,
  String   $hmac,
  String   $key = KEY,
  String   $algo = ALGO
): Bool
{
  $valid = false;
  $expected = hash_hmac($algo, json_encode([
    'user'     => $user,
    'datetime' => $datetime->format(DateTime::W3C),
  ]), $key);

  if (hash_equals($hmac, $expected)) {
    $expires = $datetime->modify(LIFETIME);
    $now = new DateTime();
    if ($expires < $now) {
      $valid = false;
    } else {
      $valid = true;
    }
  } else {
    $valid = false;
  }
  return $valid;
}
