<?php
namespace AdminRedirect;
use \DateTime;
use \Throwable;
use \Error;

const KEY          = '3NP}]PK&=->`D-F}2v*krwHUy`d+#t9J$"J7p>bX';
const ALGO         = 'sha3-512';
const LIFETIME     = '+5 seconds';
const SUCCESS_PAGE = '/success/';
const ERROR_PAGE   = '/error/';
const WP_INIT      = '../wp-load.php';
define(__NAMESPACE__ . '\\IS_WP', @file_exists(WP_INIT));

/**
 * Load WP if available, returning true/false
 * @return Bool Whether or not WP script was found & loaded
 */
function wp_init(): Bool
{
  if (IS_WP) {
    try {
      require_once WP_INIT;
      return true;
    } catch (Throwable $e) {
      return false;
    }
  } else {
    return false;
  }
}

/**
 * Login user without password
 * @param  String $user Username
 * @return Bool         If login was successful
 */
function login(String $user): Bool
{
  try {
    if (wp_init()) {
      $user = get_user_by('login', $user);
      if (! is_wp_error($user)) {
        wp_clear_auth_cookie();
        wp_set_current_user($user->ID);
        wp_set_auth_cookie($user->ID);
        return true;
      } else {
        return false;
      }
    } else {
      return true;
    }
  } catch (Throwable $e) {
    return false;
  }
}

/**
 * Redirect to a given $url
 * @param  String  $url       The URL to redirect to
 * @param  Bool    $permenant Whether or not it should be a permenant redirect
 * @return Void
 */
function redirect(String $url = '/', Bool $permanent = false): Void
{
  header(sprintf('Location: %s', $url), true, $permanent ? 301 : 302);
  exit();
}

/**
 * Verifies parsed data generated by `generate`
 * @param  String   $user        User
 * @param  DateTime $datetime    Date request generated
 * @param  String   $hmac        Given hash to check against
 * @param  String   $key         HMAC key
 * @param  String   $algo        Hashing algorithm
 * @return Bool                  If data matches HMAC and it is not expired
 */
function verify(
  String   $user,
  DateTime $datetime,
  String   $hmac,
  String   $key      = KEY,
  String   $algo     = ALGO
): Bool
{
  $valid = false;
  $expected = hash_hmac($algo, json_encode([
    'user'     => $user,
    'datetime' => $datetime->format(DateTime::W3C),
  ]), $key);

  if (hash_equals($hmac, $expected)) {
    $expires = $datetime->modify(LIFETIME);
    $now = new DateTime();
    if ($expires < $now) {
      $valid = false;
    } else {
      $valid = true;
    }
  } else {
    $valid = false;
  }
  return $valid;
}

/**
 * Checks if a list of $keys exist in $array
 * @param  Array  $array The array to check
 * @param  String $keys  The keys to check
 * @return Bool          Whether or not they exist
 * @example array_keys_exist($_GET, 'user', 'password')
 */
function array_keys_exist(Array $array, String ...$keys): Bool
{
  $exist = true;
  foreach($keys as $key) {
    if (! array_key_exists($key, $array)) {
      $exist = false;
      break;
    }
  }
  return $exist;
}

try {
  if (array_keys_exist($_GET, 'user', 'datetime', 'hmac')) {
    if (verify(
      $_GET['user'],
      new DateTime($_GET['datetime']),
      $_GET['hmac']
      ) and login($_GET['user'])) {
        redirect(SUCCESS_PAGE);
      } else {
        throw new Error('Invalid login attempt');
      }
  } else {
    throw new Error('Missing required paramaters');
  }
} catch (Throwable $e) {
  redirect(ERROR_PAGE);
}
